version: "3.9"

services:
  backend:
    build:
      context: ./backend/apilab
      dockerfile: Dockerfile
    container_name: backend_apilab
    ports:
      - "8000:8000"
    volumes:
      - ./backend/apilab:/code
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_gradio
    ports:
      - "7860:7860"    # Gradio por defecto
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: always
